doc_source/custom-platforms-scripts.md

/opt/elasticbeanstalk/bin/get-config has support to select only one key.
In a lot of cases you only want to have to value of a single key at a time. Without using these switches you need an extra application like jq to parse the json output. Using these switches you can do it without extra dependencies

Add text about the -k, -n and -o switches of get-config

---

doc_source/php-hawordpress-tutorial.md

no
**Modification 1**
Original version has wrong step number in source code. 
For example,
```markdown
**To launch an RDS DB instance in a default VPC**
1. Open the [RDS console](https://console.aws.amazon.com/rds/home)\.
1. Choose **Instances** in the navigation pane\.
1. Choose **Launch DB Instance**\.
1. Choose a **DB Engine** and preset configuration\.
```
Even though markdown interpreter of GitHub can recognize and display correct serial number, it should be corrected like this:
```markdown
**To launch an RDS DB instance in a default VPC**
1. Open the [RDS console](https://console.aws.amazon.com/rds/home)\.
2. Choose **Instances** in the navigation pane\.
3. Choose **Launch DB Instance**\.
4. Choose a **DB Engine** and preset …
```

Correct all the steps number and some indentions

---

doc_source/create_deploy_Ruby.container.md

according to `aws elasticbeanstalk list-available-solution-stacks` ruby 1.9 through 2.5 are supported now.

Updated the ruby versions supported

---

doc_source/create-deploy-python-django.md

*Issue #, if available:* #14
*Description of changes:*  
Adding further steps to comprise the configuration of Django's settings.py to configure the ALLOWED_HOSTS setting. Without this, user gets a "DisallowedHost" error after the first deployment to Beanstalk.

Additing additional required steps to Django's tutorial

---

doc_source/customize-containers-ec2.md

*Description of changes:* Clarified under which user container_commands are run. This piece of information is important and was missing. I copied the string from the command section to stay consistent. 
FYI I think we also should add the "The commands are processed in alphabetical order by name" sentence from the commands section to the container_commands as well but I haven't tested wether this would be true or not. 

Clarify under which user container_commands are run.

---

doc_source/nodejs-dynamodb-tutorial.md

none
add `-h` flag to `zip` command (i.e. `zip -h`) because without it, i get different output:
```
$ zip
adding: -
zip I/O error: Invalid argument
zip error: Temporary file failure (was zipping -)
```
BTW, I am on Windows 10 64 bit using Git Bash if it matters.

add -h flag to zip command for consistent output

---

doc_source/iam-instanceprofile.md

The documentation for Managed InstanceProfile IAM Policies provides an incomplete example of what the WorkerTier policy looks like. The IAM console confirms that some 'logs' actions are also a part of the WorkerTier policy, but it's missing from the docs.

The IAM policy snippet for AWSElasticBeanstalkWorkerTier is missing 'logs' actions

---

doc_source/eb3-tags.md

This documentation page doesn't involve creating an environment, so it doesn't seem relevant to mention the restrictions/formatting of environment names.

Remove unnecessary sentence describing environment naming requirements.

---

doc_source/eb3-scale.md

Using `scale` twice together in the Syntax section is confusing. The new wording clarifies that we expect an instance count number.

Improve wording of `eb scale scale` flag

---

doc_source/command-options-specific.md

Fixed wording for multiple sentences on Platform Specific Options page. 
Convert 5 instances of "When a the proxy server" into "When the proxy server".

Remove unnecessary 'a' on Platform Specific Options page

---

doc_source/create-deploy-python-container.md

Remove unnecessary "a" character to convert "When a the proxy" into "When the proxy".

Fix typo in Python documentation.

---

doc_source/https-storingprivatekeys.md

N/A
Across the AWS docs, the files target is quoted however in the "Storing Private Keys Securely in Amazon S3" section this was inconsistent.

Add missing quotes to files target

---

doc_source/command-options-general.md

Original reference: [Matcher](https://docs.aws.amazon.com/en_us/elasticloadbalancing/latest/APIReference/API_Matcher.html)

Separate http code matchers for Network and Application load balancers

---

doc_source/iam-instanceprofile.md

Uses a valid ARN for a dynamoDB table in the ElasticBeanstalk worker tier IAM instance profile policy example
Previously resulted in a `The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument;` when the `dynamodb` namespace is omitted.

Add service namespace for dynamo eb worker tier

---

doc_source/create_deploy_docker.container.console.md

Added observation that the authentication file has to be explicitly called .dockercfg.
I lost some hours trying to use Beanstalk with private registry, the problem was that the S3 file I was uploading was called config.json instead of .dockercfg, I tought I could call it anything since that in the Dockerrun.aws.json file i could indicate the name of the file.

added observation that the authentication file has to be explicitly called .dockercfg

---

doc_source/command-options-general.md

"aws:elasticbeanstalk:environment:process" is for configuring the target group, which is not available for classic load balancer. Removing the mentioning of "classic load balancer" to avoid customer confusion.

Fixed confusion about classic load balancer

---

doc_source/health-enhanced-serverlogs.md

Reached this conclusion via extensive testing and confirmed with an AWS support person that the apache healthd log output is in whole microseconds, not milliseconds.

Apache healthd outputs microseconds not milliseconds

---

doc_source/dotnet-core-tutorial.md

When using windows zip, sub folders are created which intern fail during deployment, address the issue by adding necessary comments

Zip should not have any sub folders

---

doc_source/https-storingprivatekeys.md

The S3 URL format in the example ebextension privatekey.config is incorrect.
The format should be <bucket-name>.s3.<region> and not <bucket-name>.s3-<region>

Corrected S3 URL format

---

doc_source/create-deploy-python-django.md

Using Python 3.7, Django 3.0.6, getting the following exception / 502 response with existing django.config WSGIPath: ebdjango/wsgi.py
ModuleNotFoundError: No module named 'ebdjango/wsgi'
During handling of the above exception, another exception occurred:
...
ImportError: Failed to find application, did you mean 'ebdjango/wsgi:application'?
*Description of changes:* Inaccuracies in the content

Fix for module not found error resulting in 502

---

doc_source/ruby-platform-procfile.md

*Issue #, if available:* n/a
I sunk several hours trying to get `Procfile` to work on the `Ruby 2.6 with Puma version 2.11.6` platform. Of course, that doesn't work because it's built on Amazon Linux and not Amazon Linux 2.
When looking at the platform versions, I thought `Amazon Linux 2018.03 v2.11.6` meant that this was later than Amazon Linux 2 (2.11.6), which is of course wrong.
I open this PR in the hopes of saving someone else wasted time in the future.

Clarify Procfile doesn't work on Puma/Passenger platforms

---

doc_source/dotnet-linux-procfile.md

Just having `web: ./dotnet-core-app1/dotnetcoreapp1.dll` in your Procfile doesn't actually work. You need to add the `dotnet` command for it to work. I found this out after spending about an hour debugging Elastic Beanstalk deployment failures.

Fix Procfile examples for .NET Core

---

doc_source/environment-configuration-debugging.md

Replace **AWSXrayWriteOnlyAccess** with **AWSXRayDaemonWriteAccess**
Based on this AWS Xray Documentation, there are only 3 IAM managed policies for Xray (AWSXrayReadOnlyAccess, AWSXRayDaemonWriteAccess, and AWSXrayFullAccess).
https://docs.aws.amazon.com/xray/latest/devguide/security_iam_id-based-policy-examples.html

Replace AWSXrayWriteOnlyAccess to AWSXRayDaemonWriteAccess

---

doc_source/health-enhanced-serverlogs.md

*Issue #, if available:* N/A
*Description of changes:* 
Changed path to rotatelogs binary.
Doing a `which rotatelogs` on a Debian Buster and Ubuntu 18.04 shows that the path is `/usr/bin/rotatelogs`

Fixed path to rotatelogs binary

---

doc_source/using-features.customenv.md

Added Windows example/clarifications, including:
- Windows example for describe-platform-version
- Changed note to explain how to get AMI ID that can be used for customization, instead of saying non-Beanstalk managed can't be used
- Link to Win virtualization type doc

Added Windows example/clarifications

---

doc_source/create-deploy-python-flask.md

Updated the Python guide to create a Flask application using Python 3.7 instead of 3.6 as 3.6 is now a deprecated platform.  Although users can still use Python 3.6, a warning is displayed when creating an application with this platform.  When using Python 3.7, this warning is not given as the platform is supported.

Update reference to Python 3.7

---

README.md

Instead of hardcoding the branch name (used to be master but now it's main) use a relative path
---

Point starting page to current branch

---

doc_source/create-deploy-python-django.md

Update the container command example to activate a venv and migrate changes to the database on deployment. Previous command was based on Amazon Linux 1, this command works better on Linux 2.
See this Stackoverflow question for additional info and discussion: https://stackoverflow.com/questions/62457165/deploying-django-to-elastic-beanstalk-migrations-failed

Update migration example in create-deploy-python-django.md

---

doc_source/single-container-docker-configuration.md

*Issue #, if available:* N/A
The output of "/opt/elasticbeanstalk/bin/get-config environment -k USER" needs to be stored in the USER variable. Hence, the command should be wrapped in back ticks (`) and not double-quotes (") in order for it to be evaluated, and not stored as a literal string. 
The current example results in the following error,
2022/12/17 17:08:46.781350 [ERROR] An error occurred during execution of command [app-deploy] - [RunAppDeployPreBuildHooks]. Stop running the command. Error: Command .platform/hooks/prebuild/01login.sh failed with error exit status 125. Stderr:unknown shorthand flag: 'k' in -k

Correcting the 01login.sh script syntax
